src/Entity/Sum.php
<?php

namespace App\Entity;

use App\Repository\SumRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SumRepository::class)
 */
class Sum
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $number_0;

    /**
     * @ORM\Column(type="integer")
     */
    private $number_1;

    /**
     * @ORM\Column(type="integer")
     */
    private $result;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber0(): ?int
    {
        return $this->number_0;
    }

    public function setNumber0(int $number_0): self
    {
        $this->number_0 = $number_0;

        return $this;
    }

    public function getNumber1(): ?int
    {
        return $this->number_1;
    }

    public function setNumber1(int $number_1): self
    {
        $this->number_1 = $number_1;

        return $this;
    }

    public function getResult(): ?int
    {
        return $this->result;
    }

    public function setResult(): self
    {
        $this->result = $this->getNumber0() + $this->getNumber1();

        return $this;
    }
}

src/Form/SumAnswerFormType.php
<?php

namespace App\Form;

use App\Dto\SumAnswer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SumAnswerFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('number_0', IntegerType::class)
            ->add('number_1', IntegerType::class)
            ->add('submit', SubmitType::class, ['label' => 'Make the sum !']);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => SumAnswer::class,
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Dto\SumAnswer;
use App\Form\SumAnswerFormType;
use App\Repository\SumRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'home', methods: ['get','post'])]
    public function index(Request $request, MessageBusInterface $bus, SumRepository $repository): Response
    {
        $session = $request->getSession();
        $messages = $session->get('messages');
        $session->remove('messages');

        $form = $this->createForm(
            SumAnswerFormType::class,
            (new SumAnswer()),
            [
                'method' => 'POST'
            ]
        );
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bus->dispatch($form->getData());
            $request->getSession()->set('messages', ['Your values has been sent.']);
            return $this->redirectToRoute('home');
        }

        return $this->render('home/index.html.twig', [
            'form' => $form->createView(),
            'messages' => $messages,
            'lastRecords' => $repository->findBy([], ['id' => 'desc'], 5)
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}
    <section>
        <h1>Sum Answer Form</h1>
        <p>Please enter the values for asking sum.</p>
        <blockquote>
            {{ form_errors(form) }}
            {% for message in messages %}
                <div class="success">
                    {{ message }}
                </div>
            {% endfor %}
        </blockquote>
        <div class="form-wrapper">
            {{ form(form) }}
        </div>
        <hr />
        <div class="records">
            <h2>5 lasts records <a href="">[refresh]</a></h2>
            {% for sumRecord in lastRecords %}
                <div>{{ sumRecord.number0}}+{{ sumRecord.number1}}={{ sumRecord.result}}</div>
            {% endfor %}
        </div>
    </section>
{% endblock %}